db:
  container_name: java_rush_test_db
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=test
  ports:
   - "3306:3306"
  volumes:
   - ../mysql:/var/lib/mysql
#app:
#  container_name: java_rush_test_app
#  image: java
#  volumes:
#   - ./:/root/jrtt
#   - ~/.mvn/:/root/.mvn
#  command: java -jar ./target/jrtt.jar
